# Generated by Django 4.2.7 on 2024-02-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='email',
            new_name='customer_email',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.DeleteModel(
            name='OrderConfirmation',
        ),
    ]
